version: '3.8'

services:
  tau-bench-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TAU_BENCH_LOG_DIR=/app/logs
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
      - ./api_results:/app/api_results
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add nginx for production load balancing
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tau-bench-api
    restart: unless-stopped
    profiles:
      - production